// Code generated by MockGen. DO NOT EDIT.
// Source: ../validator.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Gunvolt24/wb_l0/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockOrderValidator is a mock of OrderValidator interface.
type MockOrderValidator struct {
	ctrl     *gomock.Controller
	recorder *MockOrderValidatorMockRecorder
}

// MockOrderValidatorMockRecorder is the mock recorder for MockOrderValidator.
type MockOrderValidatorMockRecorder struct {
	mock *MockOrderValidator
}

// NewMockOrderValidator creates a new mock instance.
func NewMockOrderValidator(ctrl *gomock.Controller) *MockOrderValidator {
	mock := &MockOrderValidator{ctrl: ctrl}
	mock.recorder = &MockOrderValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderValidator) EXPECT() *MockOrderValidatorMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockOrderValidator) Validate(ctx context.Context, order *domain.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockOrderValidatorMockRecorder) Validate(ctx, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockOrderValidator)(nil).Validate), ctx, order)
}
